export const GET_MOVIES_STERT = 'GET_MOVIES_STERT';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';

export const GET_PLANETS_START = 'GET_PLANETS_START';
export const GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS';
export const GET_PLANETS_FAIL = 'GET_PLANETS_SUCCESS';
